spring.application.name=webflux-playground

sec=sec03

# Enable this only for sec01
spring.main.allow-bean-definition-overriding=true

# To show SQL
logging.level.org.springframework.r2dbc=TRACE

#spring.sql.init.mode=always
# Use schema-locations for CREATE TABLE statements
spring.sql.init.schema-locations=classpath:sql/data.sql
#spring.sql.init.data-locations=classpath:sql/data.sql


